// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/jwttoken/jwt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenMakerInterface is a mock of TokenMakerInterface interface.
type MockTokenMakerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMakerInterfaceMockRecorder
}

// MockTokenMakerInterfaceMockRecorder is the mock recorder for MockTokenMakerInterface.
type MockTokenMakerInterfaceMockRecorder struct {
	mock *MockTokenMakerInterface
}

// NewMockTokenMakerInterface creates a new mock instance.
func NewMockTokenMakerInterface(ctrl *gomock.Controller) *MockTokenMakerInterface {
	mock := &MockTokenMakerInterface{ctrl: ctrl}
	mock.recorder = &MockTokenMakerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenMakerInterface) EXPECT() *MockTokenMakerInterfaceMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockTokenMakerInterface) CreateToken(username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockTokenMakerInterfaceMockRecorder) CreateToken(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockTokenMakerInterface)(nil).CreateToken), username)
}

// VerifyToken mocks base method.
func (m *MockTokenMakerInterface) VerifyToken(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenMakerInterfaceMockRecorder) VerifyToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenMakerInterface)(nil).VerifyToken), tokenString)
}
