// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Inventory struct {
	InventoryID int32  `json:"inventory_id"`
	UserID      int32  `json:"user_id"`
	ItemType    string `json:"item_type"`
	Quantity    int32  `json:"quantity"`
}

type Item struct {
	ItemID    int32  `json:"item_id"`
	ItemType  string `json:"item_type"`
	ItemPrice int16  `json:"item_price"`
}

type Transfer struct {
	TransferID   int32  `json:"transfer_id"`
	FromUsername string `json:"from_username"`
	ToUsername   string `json:"to_username"`
	Amount       int32  `json:"amount"`
}

type User struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Coins    int32  `json:"coins"`
}
