// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	BuyItem(ctx context.Context, arg BuyItemParams) error
	CreateMoneyTransfer(ctx context.Context, arg CreateMoneyTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetInventory(ctx context.Context, userID int32) ([]Inventory, error)
	GetItemFromStore(ctx context.Context, itemType string) (Item, error)
	GetTransfersWithUser(ctx context.Context, username string) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, username string) (User, error)
	GetUserViaID(ctx context.Context, userID int32) (User, error)
	UpdateTwoUsersBalance(ctx context.Context, arg UpdateTwoUsersBalanceParams) ([]User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error)
}

var _ Querier = (*Queries)(nil)
