// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store.sql

package db

import (
	"context"
)

const getItemFromStore = `-- name: GetItemFromStore :one
SELECT item_id, item_type, item_price FROM Items
WHERE item_type = $1
LIMIT 1 
FOR SHARE
`

func (q *Queries) GetItemFromStore(ctx context.Context, itemType string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemFromStore, itemType)
	var i Item
	err := row.Scan(&i.ItemID, &i.ItemType, &i.ItemPrice)
	return i, err
}
